package:
    name: tinycc
    version: 0.9.27
source:
    path: ../../
build:
    binary_relocation: true
    detect_binary_files_with_prefix: true
    number: 4

about:
    home: http://repo.or.cz/w/tinycc.git 
    license: LGPL
    summary: Tiny C Compiler - C Scripting Everywhere - The Smallest ANSI C compiler
